latex Derivation_of_Single_Configuration_Ansatz 
bibtex Derivation_of_Single_Configuration_Ansatz
latex Derivation_of_Single_Configuration_Ansatz
latex Derivation_of_Single_Configuration_Ansatz
pdflatex Derivation_of_Single_Configuration_Ansatz
evince Derivation_of_Single_Configuration_Ansatz.pdf
